server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: 182.254.137.214:8848
        username: nacos
        password: evanevan123
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://182.254.137.214:3307/seata_order
    username: root
    password: EVANway123

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml