server:
  port: 8010
spring:
  application:
    name: rabbitmq-provider
  rabbitmq:
    host: 182.254.137.214
    port: 5672
    username: admin
    password: evan123
    virtual-host: my_vhost
    # 生产者——确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    # 生产者——确认消息已发送到队列(Queue)
    publisher-returns: true

